name: Build and Test

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version'
        type: string
        required: true
        default: '20.x'

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  setup-node:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

  lint:
    runs-on: ubuntu-latest
    needs: setup-node
    steps:
      - name: Run format check
        run: npm run format

      - name: Run lint check
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: setup-node
    steps:
      - name: Build the project
        run: npm run build

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run unit tests with coverage
        run: npm test:cov

      - name: Upload unit test coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage

  e2e-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run e2e tests without coverage (develop)
        if: github.ref == 'refs/heads/develop'
        run: npm test:e2e

      - name: Run e2e tests with coverage (master)
        if: github.ref == 'refs/heads/master'
        run: npm test:e2e:cov

      - name: Upload e2e test coverage report
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: e2e-coverage-report
          path: coverage-e2e
