name: Node.js CI

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      - master

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    with:
      node-version: '20.x'
