# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "develop", "main", "release/*" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run format check
      run: npm run format

    - name: Run lint check
      run: npm run lint

    - name: Build the project
      run: npm run build

    - name: Run unit tests with coverage
      run: npm run test:cov

    - name: Upload unit test coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage

    - name: Run e2e tests without coverage (develop)
      if: github.ref == 'refs/heads/develop'
      run: npm run test:e2e

    - name: Run e2e tests with coverage (main)
      run: npm run test:e2e:cov
      if: github.ref == 'refs/heads/main'

    - name: Upload e2e test coverage report
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: e2e-coverage-report
        path: coverage-e2e
